SELECT
    PD.DTFAT AS dt,
    SUM(PD.VLTOTAL) AS vltotal,
    COUNT(DISTINCT PD.codcli) AS qtcli
FROM
    PCPEDC PD
WHERE
	PD.DTFAT BETWEEN TO_DATE('01/10/2024', 'dd/mm/yyyy') AND TO_DATE('31/03/2025', 'dd/mm/yyyy')
    AND PD.POSICAO = 'F'
    AND PD.CONDVENDA = 7
    AND PD.NUMPED IN (SELECT NUMPED FROM PCPEDI WHERE TIPOENTREGA <> 'EN')
GROUP BY
    PD.DTFAT
ORDER BY
	PD.DTFAT;